### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bardobrado** [MacFJA/svelte-persistent-store#1]
Got this error trying to use it. I'm using saper, svelte, firebase and babylonjs. I dont know why.

```
defined/home/rahto/www/xblazy.com/node_modules/@macfja/svelte-persistent-store/dist/index.js:135
      return getBrowserStorage(window.localStorage);
                               ^

ReferenceError: window is not defined
    at Object.localStorage (/home/rahto/www/xblazy.com/node_modules/@macfja/svelte-persistent-store/dist/index.js:135:32)
    at Object.<anonymous> (/home/rahto/www/xblazy.com/__sapper__/dev/server/server.js:1229:84)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> Server crashed
```

**Comment by MacFJA** [comment]
`localStorage` (as well as `sessionStorage`) are only available inside a Browser, where `window` is defined.
(https://developer.mozilla.org/en-US/docs/Web/API/Storage)

So, the `localStorage` won't work in the server context.

You probably need to implement a new [`Storage`](https://github.com/MacFJA/svelte-persistent-store/blob/main/src/index.ts#L17) that use the Firebase database.
I can help you with that I you need

**Comment by MacFJA** [comment]
The version `1.0.1` and `1.0.2` should solve this issue.

If not don't hesitate to reopen this issue.
