### ISSUE TITLE
Vite exlude not works, new Sveltekit breaks

### ISSUE THREAD

**Issue by bitdom8** [MacFJA/svelte-persistent-store#16]
@macfja/svelte-persistent-store breaks and not be excluded during build:

t async```
 respond$1 (file:///C:/Users/Administrator/Documents/clienttry/.svelte-kit/output/server/index.js:1480:13)
> 500 /
    at file:///C:/Users/Administrator/Documents/clienttry/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.294_sass@1.49.9+svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index2.js:975:11
    at save (file:///C:/Users/Administrator/Documents/clienttry/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.294_sass@1.49.9+svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index2.js:1194:4)
    at visit (file:///C:/Users/Administrator/Documents/clienttry/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.294_sass@1.49.9+svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index2.js:1085:3)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by bitdom8** [comment]
I tried without using this, it builds

**Comment by bitdom8** [comment]
Can we include this on the svelte:head so that it won't build and error
