### ISSUE TITLE
ReferenceError: require is not defined in ES module scope, you can use import instead

### ISSUE THREAD

**Issue by SwiftWinds** [MacFJA/svelte-persistent-store#18]
When using this package with SvelteKit, I get:

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/matt/Development/ucsb-fake-badge/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at 607 (file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:66:85), <anonymous>:1:1)
    at Object.607 (file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:66:85)
    at __webpack_require__ (file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:448:37)
    at file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:450:12
    at file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:451:5
    at file:///Users/matt/Development/ucsb-fake-badge/.svelte-kit/output/server/entries/pages/index.svelte.js:452:3
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async Promise.all (index 1)
> 500 /
    at file:///Users/matt/Development/ucsb-fake-badge/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.320_svelte@3.47.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:989:11
    at save (file:///Users/matt/Development/ucsb-fake-badge/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.320_svelte@3.47.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1209:4)
    at visit (file:///Users/matt/Development/ucsb-fake-badge/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.320_svelte@3.47.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1100:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.
```

And it goes away when I remove `svelte-persistent-store` from my project. Any ideas how to fix this?

**Comment by MacFJA** [comment]
From my investigation ([see here](https://discord.com/channels/457912077277855764/965696490351767623/965705744278257695)) I seem that the issue came from the dependency [`esserializer`](https://www.npmjs.com/package/esserializer).

I did some tests, and sadly it appear that I won't be able to fix/do a workaround on my side.

**Comment by martinkovacik** [comment]
To fix the error change this line https://github.com/MacFJA/svelte-persistent-store/blob/c6ad468a26ba0222679c67cc506e8fd17ef31284/src/index.ts#L2
to this: `import * as ESSerializer from "esserializer"`

**Comment by extremegf** [comment]
I solved this problem by downgrading to 1.2.0.

**Comment by gyurielf** [comment]
Same here.

**Comment by lorenzodonadio** [comment]
downgrading to 1.2.0 also worked for me
